### ISSUE TITLE
Formatting conflicts

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/M6-Time-High-Card#10]
A small request.  please see below video.
https://www.youtube.com/watch?v=v8xOpfXHqdo

Reason is I keep removing tabs and poorly formatted code.
If you do the following **in order**, the code will be better autoformatted saving time on fixing formatting.

- Set tabs to spaces (not tabs)
- Set maximum line length to 80 per above video
- Directly underneath where you set the line length, set tabs/spaces to 3
- Setup the other bracket formatting IAW professor's instructions

This can be done really quick.

**Comment by hmason55** [comment]
Yeah I've been trying to keep this up when I code, sometimes I forget to ctrl+shift+F before I save and commit.
