### ISSUE TITLE
Phase3.txt is working properly, but it should be deleted from this project soon

### ISSUE THREAD

**Issue by p12345vls** [team-makeSmart/M6-Time-High-Card#11]

**Comment by p12345vls** [comment]
Phase3.txt is from the previous project

**Comment by hmason55** [comment]
Resolved in commit [1b1a131ae0b06b82474ebff0357274b8eb320a0f](https://github.com/team-makeSmart/M6-Time-High-Card/commit/1b1a131ae0b06b82474ebff0357274b8eb320a0f)
