### ISSUE TITLE
Phase 1: Model-View-Controller Design Pattern

### ISSUE THREAD

**Issue by p12345vls** [team-makeSmart/M6-Time-High-Card#12]
- [x] You need to redesign last week's code into the Model-View-Controller Design Pattern.
There is a sample for number3 on pg 709.
This will help you as you take a look at what code needs to be moved around.
 - [x] Make sure that the game still works as it did last week.

**Comment by hmason55** [comment]
Was the mvc design pattern completed for this phase?

**Comment by p12345vls** [comment]
I am not sure what this description is asking  "This will help you as you take a look at what code needs to be moved around."

**Comment by p12345vls** [comment]
This is the " sample for number3 on pg 709."
<img width="595" alt="screen shot 2018-04-06 at 3 01 29 pm" src="https://user-images.githubusercontent.com/32381448/38446163-7a493074-39ab-11e8-8816-01016f838f93.png">

**Comment by hmason55** [comment]
It's weird that he would just show us a UML diagram as an example of an MVC. I'm pretty sure they are supposed to look like a flow chart but I've never made one before.

[Here's a sample one from wikipedia](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller)

**Comment by p12345vls** [comment]
My guess is that "sample for number3 " means for the phase3 and in page 709 there is a project related to our assignment

<img width="725" alt="screen shot 2018-04-06 at 3 14 04 pm" src="https://user-images.githubusercontent.com/32381448/38446511-58f5ec76-39ad-11e8-9965-0d2d44cd59f2.png">

**Comment by p12345vls** [comment]
This is the code for the above:

`class CounterView
{
	
	public void Display(int counterValue)
	{
		System.out.println(counterValue);
	}
	
} 

class CounterModel extends CounterView
{
	
	private int counter;
	private int init;

	
	public CounterModel(int initialValue)
	{
		super();
		counter = initialValue;
		init = initialValue;
	}

	
	public void increment()
	{
		counter++;
		Display(counter);
	}

	
	public void resetCounter()
	{
		counter = init;
	}
}


class CounterController extends CounterModel
{
	
	private int startValue;
	private int endValue;

	public CounterController(int startValue, int endValue)
	{
		super(startValue);
		this.startValue = startValue;
		this.endValue = endValue;
	}

	
	public void Start()
	{
		
		for (int i = startValue; i < endValue; i++)
		{
			try
			{
				Thread.sleep(1000);
			} catch (InterruptedException e)
			{
				System.out.println("Error: interrupted program.");
			}
			
			increment();
		}
		resetCounter();
	}
	
}

class Main
{

	public static void main(String args[])
	{
		
		CounterController control1 = new CounterController(15, 20);
		CounterController control2 = new CounterController(0, 20);
		CounterController control3 = new CounterController(10, 25);
		
		control1.Start();
		System.out.println("---");
		control2.Start();
		System.out.println("---");
		control3.Start();
		System.out.println("---");
	}
}`

**Comment by hmason55** [comment]
Alright, I'm going to reopen this one until the MVC is complete

**Comment by p12345vls** [comment]
unassign myself until I have a clear understanding as to what is to be done

**Comment by p12345vls** [comment]
Starting now to convert Phase1 to MVC

**Comment by p12345vls** [comment]
For some reason sometimes I push with my other git account.. I am trying to get familiar with working with git from eclipse. 
Phase1 ready.
