### ISSUE TITLE
AI's hand does not reduce in program

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/M6-Time-High-Card#7]
When the AI plays a card, program does not remove a card from the AI's hand.

**Comment by hmason55** [comment]
I've fixed this bug like 5 or 6 times already, not sure how it keeps coming back. See [Issue #32](https://github.com/team-makeSmart/GUI-Cards/issues/32)

**Comment by mdoussias** [comment]
This is another concern.... I've noticed several things I've fixed keep coming back as well.  Especially formatting and notes.   Small fixes, but it eats time.

Every pull request I put I make sure I am updating the most current document.  I'm worried someone is working off their computer separately and putting back in old bugs.

**Comment by mdoussias** [comment]
To be fair, I may have approved pull requests with bugs being put back in without noticing.  
Probably something we need to get cleaner about.

**Comment by mdoussias** [comment]
I'm not getting this error anymore with what the phase3.txt file that was just uploaded.

**Comment by p12345vls** [comment]
That is the file we uploaded yesterday, but without the delay between the rounds

**Comment by mdoussias** [comment]
Ok so we can close out this issue.

**Comment by hmason55** [comment]
This bug was reintroduced in commit [66b8ef86c8a411d579b750900320dbf36a10bef6](https://github.com/team-makeSmart/M6-Time-High-Card/commit/66b8ef86c8a411d579b750900320dbf36a10bef6)

On lines 1616 through 1633

**Comment by hmason55** [comment]
Make sure you push the .class files from the /bin directory or else some changes we make will get overwritten by your local .class metadata

**Comment by hmason55** [comment]
Resolved in commit [7776a80221e610be057ba07a4558fd352bc95f4d](https://github.com/team-makeSmart/M6-Time-High-Card/commit/7776a80221e610be057ba07a4558fd352bc95f4d)
