### ISSUE TITLE
Card left sometimes after round ends.

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/M6-Time-High-Card#8]
- [ ] Not every round.  But sometimes the AI has a card left on the table when the game ends.

Unsure of reason, but seems to happen when **player** loses the last play.

**Comment by mdoussias** [comment]
This was mentioned in issue #1

**Comment by p12345vls** [comment]
I am thinking if we can try to fix the other bug too and resubmit the phase3.txt and loosing the the 10%. If we leave it as it is we might loose more.

**Comment by mdoussias** [comment]
Yeah it sucks, last week was tough, but I worry we won't have time to fix now.  
I am looking how to fix bugs now.

**Comment by mdoussias** [comment]
Not completely sure, but regarding this bug, I think this error may be found in **phase3.computerPlayCard()**   

It needs to check if the game has ended and not play another card, if so.
