### ISSUE TITLE
Phase1.java crashes after a couple cards are played

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/M6-Time-High-Card#9]
Phase1.java crashes after a couple cards are played

I believe this was fixed several iterations ago.  

Currently the Phase3.txt file in Module 6 (NOTE outside of SRC folder) works, though it has some bugs.  Conflicts will need resolved.

**Comment by mdoussias** [comment]
I'm just posting bugs as I see them.

**Comment by hmason55** [comment]
This is due to the remaining card bug, which is also linked to when the user clicks a card, a different one is played.

**Comment by p12345vls** [comment]
It works now
